import {get, post, put, del} from 'koa-router-decors';
  
export default class maintenance_quote{
  @get(`/purchase/message/search/maintenance_quotation_order`)
  async GetOrderList(ctx){
      ctx.body = {
          result: true,
          data:{
                "current_page": 1,
                "data": [
                  {
                    "_id": 658804628996096,
                    "created_at": "2021-04-10 09:30:43",
                    "updated_at": "2021-04-10 09:30:43",
                    "deleted_at": null,
                    "order_num": "WS2104100003",
                    "created_uid": 10,
                    "created_name": "anle",
                    "coid": 2,
                    "branch": 11,
                    "origin_type": 0,
                    "order_type": 20040000,
                    "type": 41,
                    "check_type": 0,
                    "status": 0,
                    "level": 0,
                    "max_level": 0,
                    "pay_id": 1,
                    "pay_day": 30,
                    "caption_account_id": 1,
                    "caption_account_code": "1001",
                    "caption_account_name": "库存现金",
                    "transaction_id": 0,
                    "tax_rate": 13,
                    "has_taxes": true,
                    "member_id": 7,
                    "member_name": "anle2",
                    "customer_type": 1,
                    "customer_id": 1,
                    "customer_num": "0001",
                    "customer_name": "林德叉车有限公司",
                    "payer_id": 1,
                    "payer_num": "001",
                    "payer_name": "0027",
                    "receive_id": 1,
                    "receive_num": "001",
                    "receive_name": "0027",
                    "contract_fee_tax": "12.00",
                    "contract_fee": null,
                    "supplier_id": null,
                    "deduct_id": null,
                    "remark": null,
                    "deduct_users": null,
                    "check_user": []
                  },
                  {
                    "_id": 658804020232192,
                    "created_at": "2021-04-10 09:30:06",
                    "updated_at": "2021-04-10 09:30:06",
                    "deleted_at": null,
                    "order_num": "WS2104100002",
                    "created_uid": 10,
                    "created_name": "anle",
                    "coid": 2,
                    "branch": 11,
                    "origin_type": 0,
                    "order_type": 20040000,
                    "type": 41,
                    "check_type": 0,
                    "status": 0,
                    "level": 0,
                    "max_level": 0,
                    "pay_id": 1,
                    "pay_day": 30,
                    "caption_account_id": 1,
                    "caption_account_code": "1001",
                    "caption_account_name": "库存现金",
                    "transaction_id": 0,
                    "tax_rate": 13,
                    "has_taxes": true,
                    "member_id": 7,
                    "member_name": "anle2",
                    "customer_type": 1,
                    "customer_id": 1,
                    "customer_num": "0001",
                    "customer_name": "林德叉车有限公司",
                    "payer_id": 1,
                    "payer_num": "001",
                    "payer_name": "0027",
                    "receive_id": 1,
                    "receive_num": "001",
                    "receive_name": "0027",
                    "contract_fee_tax": "0.00",
                    "contract_fee": 0,
                    "supplier_id": 0,
                    "deduct_id": 0,
                    "remark": null,
                    "deduct_users": null,
                    "check_user": []
                  },
                  {
                    "_id": 658798326120448,
                    "created_at": "2021-04-10 09:24:18",
                    "updated_at": "2021-04-10 09:24:18",
                    "deleted_at": null,
                    "order_num": "WS2104100001",
                    "created_uid": 10,
                    "created_name": "anle",
                    "coid": 2,
                    "branch": 11,
                    "origin_type": 0,
                    "order_type": 20040000,
                    "type": 41,
                    "check_type": 0,
                    "status": 0,
                    "level": 0,
                    "max_level": 0,
                    "pay_id": 1,
                    "pay_day": 30,
                    "caption_account_id": 1,
                    "caption_account_code": "1001",
                    "caption_account_name": "库存现金",
                    "transaction_id": 0,
                    "tax_rate": 13,
                    "has_taxes": true,
                    "member_id": 7,
                    "member_name": "anle2",
                    "customer_type": 1,
                    "customer_id": 1,
                    "customer_num": "0001",
                    "customer_name": "林德叉车有限公司",
                    "payer_id": 1,
                    "payer_num": "001",
                    "payer_name": "0027",
                    "receive_id": 1,
                    "receive_num": "001",
                    "receive_name": "0027",
                    "contract_fee_tax": "0.00",
                    "contract_fee": 0,
                    "supplier_id": 0,
                    "deduct_id": 0,
                    "remark": null,
                    "deduct_users": null,
                    "check_user": []
                  },
                  {
                    "_id": 657930296016896,
                    "created_at": "2021-04-09 18:41:18",
                    "updated_at": "2021-04-10 09:47:08",
                    "deleted_at": null,
                    "order_num": "WS2104090004",
                    "created_uid": 10,
                    "created_name": "anle",
                    "coid": 2,
                    "branch": 11,
                    "origin_type": 0,
                    "order_type": 20040000,
                    "type": 41,
                    "check_type": 0,
                    "status": 0,
                    "level": 0,
                    "max_level": 1,
                    "pay_id": 1,
                    "pay_day": 30,
                    "caption_account_id": 1,
                    "caption_account_code": "1001",
                    "caption_account_name": "库存现金",
                    "transaction_id": 0,
                    "tax_rate": 13,
                    "has_taxes": true,
                    "member_id": 7,
                    "member_name": "anle2",
                    "customer_type": 1,
                    "customer_id": 1,
                    "customer_num": "0001",
                    "customer_name": "林德叉车有限公司",
                    "payer_id": 1,
                    "payer_num": "001",
                    "payer_name": "0027",
                    "receive_id": 1,
                    "receive_num": "001",
                    "receive_name": "0027",
                    "contract_fee_tax": "0.00",
                    "contract_fee": 0,
                    "supplier_id": 0,
                    "deduct_id": 0,
                    "remark": null,
                    "deduct_users": null,
                    "check_user": [
                      {
                        "_id": 658820769857536,
                        "uuid": "6071039c6cc815026a2c0821",
                        "coid": 2,
                        "order_type": 20040000,
                        "order_id": 657930296016896,
                        "order_num": "WS2104090004",
                        "uid": 6,
                        "uname": "测试01",
                        "level": 1,
                        "status": 1,
                        "check_remark": null,
                        "remark": null,
                        "created_at": "2021-04-10T01:47:08.000000Z",
                        "updated_at": null,
                        "deleted_at": null
                      }
                    ]
                  }
                ],
                "first_page_url": "http://192.168.2.47/api/v1/purchase/message/search/maintenance_sales_order?page=1",
                "from": 1,
                "last_page": 1,
                "last_page_url": "http://192.168.2.47/api/v1/purchase/message/search/maintenance_sales_order?page=1",
                "links": [
                  {
                    "url": null,
                    "label": "&laquo; Previous",
                    "active": false
                  },
                  {
                    "url": "http://192.168.2.47/api/v1/purchase/message/search/maintenance_sales_order?page=1",
                    "label": 1,
                    "active": true
                  },
                  {
                    "url": null,
                    "label": "Next &raquo;",
                    "active": false
                  }
                ],
                "next_page_url": null,
                "path": "http://192.168.2.47/api/v1/purchase/message/search/maintenance_sales_order",
                "per_page": 10,
                "prev_page_url": null,
                "to": 4,
                "total": 4,
              "status": 200
            },
              "status": 200
            
     }
  }

  @get(`/purchase/message/detail`)
  async GetOrderDetail(ctx){
      ctx.body = {
        "data": {
          "_id": 657930296016896,
          "created_at": "2021-04-09 18:41:18",
          "updated_at": "2021-04-10 09:47:08",
          "deleted_at": null,
          "order_num": "WS2104090004",
          "created_uid": 10,
          "created_name": "anle",
          "coid": 2,
          "branch": 11,
          "origin_type": 0,
          "order_type": 20040000,
          "type": 41,
          "check_type": 0,
          "status": 0,
          "level": 0,
          "max_level": 1,
          "pay_id": 1,
          "pay_day": 30,
          "caption_account_id": 1,
          "caption_account_code": "1001",
          "caption_account_name": "库存现金",
          "transaction_id": 0,
          "tax_rate": 13,
          "has_taxes": true,
          "member_id": 7,
          "member_name": "anle2",
          "customer_type": 1,
          "customer_id": 1,
          "customer_num": "0001",
          "customer_name": "林德叉车有限公司",
          "payer_id": 1,
          "payer_num": "001",
          "payer_name": "0027",
          "receive_id": 1,
          "receive_num": "001",
          "receive_name": "0027",
          "contract_fee_tax": "0.00",
          "contract_fee": 0,
          "supplier_id": 0,
          "deduct_id": 0,
          "remark": null,
          "deduct_users": null,
          "company": {
            "id": 2,
            "type": 2,
            "name": "云仓联",
            "hb": "CNY",
            "address": "江苏省苏州市相城区新尚商业广场A座1001室",
            "pay_address": "",
            "s_address": "",
            "status": true,
            "remark": null,
            "created_at": "2020-12-04T12:00:34.000000Z",
            "updated_at": "2020-12-04T12:00:34.000000Z",
            "deleted_at": null
          },
          "supplier_message": {
            "id": 1,
            "num": "0001",
            "name": "林德叉车有限公司",
            "label": "1",
            "short_name": "林德",
            "address_one": "",
            "addresss_one": "",
            "address_two": "",
            "addresss_two": "",
            "email": "",
            "mobile_one": null,
            "mobile_two": null,
            "taxpayer_num": "7386465",
            "tax_rate": "0.00",
            "discount": "1",
            "account_num": "",
            "type": 3,
            "type_name": "001",
            "customer_type": 1,
            "pay_id": 1,
            "pay_day": 30,
            "remark": null,
            "created_at": "2020-12-05T06:10:17.000000Z",
            "updated_at": "2020-12-07T06:02:25.000000Z",
            "deleted_at": null
          },
          "caption_account": {
            "code": "1001",
            "name": "库存现金",
            "remark": null,
            "id": 1,
            "caption_parents": null
          },
          "check_user": [
            {
              "_id": 658820769857536,
              "uuid": "6071039c6cc815026a2c0821",
              "coid": 2,
              "order_type": 20040000,
              "order_id": 657930296016896,
              "order_num": "WS2104090004",
              "uid": 6,
              "uname": "测试01",
              "level": 1,
              "status": 1,
              "check_remark": null,
              "remark": null,
              "created_at": "2021-04-10T01:47:08.000000Z",
              "updated_at": null,
              "deleted_at": null
            }
          ],
          "material_message": [],
          "pay_message": {
            "id": 1,
            "name": "月结",
            "day": 30,
            "status": 1,
            "remark": "",
            "created_at": "2020-12-05 13:12:45",
            "updated_at": "2020-12-05 13:12:45",
            "deleted_at": null
          },
          "bill_message": {
            "id": 41,
            "pid": 2,
            "branchs": null,
            "level": 2,
            "name": "采购询价单",
            "order_type": 10010030,
            "caption_account_id": 0,
            "caption_account_code": "",
            "caption_account_name": "",
            "sort": 0,
            "can_deleted": false,
            "remark": null,
            "created_at": "2020-08-10 09:47:44",
            "updated_at": null,
            "deleted_at": null
          },
          "branch_message": {
            "id": 1,
            "type": 11,
            "title": "全事业部",
            "material_type": "1,5,2,6,3,7,4,8",
            "status": true,
            "desc": "",
            "created_at": "2020-12-04 20:11:49",
            "updated_at": "2020-12-04 20:11:49",
            "deleted_at": null,
            "MaterialName": [
              {
                "id": 1,
                "type": "forklift",
                "name": "叉车",
                "sort": 8,
                "is_deleted": false,
                "status": true,
                "remark": null,
                "deleted_at": null
              },
              {
                "id": 2,
                "type": "truck",
                "name": "高空作业车",
                "sort": 7,
                "is_deleted": false,
                "status": true,
                "remark": "1232",
                "deleted_at": null
              },
              {
                "id": 3,
                "type": "battery",
                "name": "电瓶",
                "sort": 6,
                "is_deleted": false,
                "status": true,
                "remark": null,
                "deleted_at": null
              },
              {
                "id": 4,
                "type": "charger",
                "name": "充电器",
                "sort": 5,
                "is_deleted": false,
                "status": true,
                "remark": null,
                "deleted_at": null
              },
              {
                "id": 5,
                "type": "fitting",
                "name": "属具",
                "sort": 4,
                "is_deleted": false,
                "status": true,
                "remark": null,
                "deleted_at": null
              },
              {
                "id": 6,
                "type": "fork",
                "name": "货叉",
                "sort": 3,
                "is_deleted": false,
                "status": true,
                "remark": null,
                "deleted_at": null
              },
              {
                "id": 7,
                "type": "accessory",
                "name": "配件",
                "sort": 2,
                "is_deleted": false,
                "status": true,
                "remark": null,
                "deleted_at": null
              },
              {
                "id": 8,
                "type": "equipment",
                "name": "生产设备",
                "sort": 1,
                "is_deleted": false,
                "status": true,
                "remark": null,
                "deleted_at": null
              }
            ]
          }
        },
        "status": 200
      }
         
            
     }
}